import type { Metadata } from "next";
import { Montserrat_Alternates } from "next/font/google";
import "../globals.css";
import styles from "./main.module.css";
import Header from "./components/header/header";

const montserrat = Montserrat_Alternates({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--montserrat-alternates",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${styles}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
